[versions]
kotlin = "1.8.0"
kotlinCoroutines = "1.4.2"
shadow = "8.1.1"
log4j = "2.20.0"
simpleCloudController = "1.0.19-EXPERIMENTAL"
commonsIoVersion = "2.15.1"
configurateVersion = "4.1.2"
cliktVersion = "4.3.0"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jSlf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

# app.simplecloud.controller:controller-shared:1.0.19-EXPERIMENTAL
simpleCloudController = { module = "app.simplecloud.controller:controller-shared", version.ref = "simpleCloudController" }

commonsIo = { module = "commons-io:commons-io", version.ref = "commonsIoVersion" }

configurateYaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurateVersion" }
configurateGson = { module = "org.spongepowered:configurate-gson", version.ref = "configurateVersion" }
configurateExtraKotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurateVersion" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "cliktVersion" }

[bundles]
log4j = [
    "log4jCore",
    "log4jApi",
    "log4jSlf4j"
]
configurate = [
    "configurateYaml",
    "configurateGson",
    "configurateExtraKotlin"
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }